config/routes.rb
Flickr::Application.routes.draw do
  resources :comments

  resources :users

  resources :videos

  resources :photos do
    collection do
      post "search", to: "photos#search"
    end
  end

  resources :sessions, only: [:new, :create, :destroy]

  get 'logout', to: "sessions#destroy"

  root 'welcome#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
  belongs_to :user
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user

  mount_uploader :upload, UploadUploader

  scoped_search on: [:title, :description]
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password validations: false

  validates :username, :email, presence: true
  validates :username, :email, uniqueness: true

  has_many :photos
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def set_current_user
    if session[:user_id]
      @current_user = User.find(session[:user_id])
    end
  end

  def require_current_user
    set_current_user
    redirect_to new_session_path unless @current_user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_current_user

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.commentable = Photo.find(params[:photo_id])
    @comment.user = @current_user

    @comment.save
    redirect_to :back
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  before_action :require_current_user, except: [:show, :search]

  def index
    render text: "Coming soon!"
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    @photo.user = @current_user
    @photo.save

    redirect_to photo_path(@photo)
  end

  def search
    @results = Photo.search_for params[:query]
  end

  private

  def photo_params
    params.require(:photo).permit(:title, :description, :upload)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: params[:user][:email])

    if @user && login_valid?(@user)
      session[:user_id] = @user.id
      redirect_to photos_path
    else
      flash[:error] = "You stupid fuck you can't even type in a password."
      redirect_to new_session_path
    end
  end

  def destroy
    reset_session
    redirect_to new_session_path
  end

  private

  def login_valid?(user)
    if Rails.env.test?
      if params[:user][:password_digest] == user.password_digest
        return true
      end
    elsif @user.authenticate(params[:user][:password])
      return true
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to photos_path
    else
      render action: :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flickr</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h2>Search for a Flickr Photo</h2>
<%= form_tag(search_photos_path) do -%>
  <%= search_field_tag :query -%>
  <%= submit_tag "Search" %>
<% end %>
<p> A random paragraph so the app updates! Huzzah! </p>
<%= yield %>

</body>
</html>

app/views/photos/new.html.erb
<h1>Upload a Flickr Photo</h1>

<%= form_for @photo do |f| %>
  <div>Title: <%= f.text_field :title %></div>
  <div>Description: <%= f.text_area :description %></div>
  <div>File: <%= f.file_field :upload %></div>
  <div><%= f.submit "Upload Photo" %></div>
<% end %>

app/views/photos/search.html.erb
The results of your search look like this:

<ul>
  <% @results.each do |result| %>
    <li><%= result.title %></li>
  <% end %>
</ul>

app/views/photos/show.html.erb
<h1><%= @photo.title %></h1>

<%= image_tag @photo.upload_url %>
<p><%= @photo.description %></p>
<p>Uploaded by <b><%= @photo.user.username %></b> on <%= @photo.created_at %>.</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign up to Flickr</h1>
<%= form_for @user do |f| %>
  <%= f.error_messages %>

  <div>Username: <%= f.text_field :username %></div>
  <div>Email: <%= f.text_field :email %></div>
  <div>Password: <%= f.password_field :password %></div>
  <div>Confirm: <%= f.password_field :password_confirmation %></div>
  <div><%= f.submit "Sign Up" %></div>
<% end %>